### ISSUE TITLE
import biocjson error for python 2.7

### ISSUE THREAD

**Issue by prasad676** [yfpeng/bioc#8]
We are using bioc (1.2.3) version for python 2.7.15.  We are not able to import biocjson for py2. 
We checked the biocjson code and it seems like it is compatible with py3. 
Could you please give us solution to use biocjson for py2 as we are using negbio + BLLIPParser ?
![image](https://user-images.githubusercontent.com/11713132/54282410-f43aa700-45c1-11e9-96af-875973325666.png)

**Comment by yfpeng** [comment]
Because Python 2 support ends in 2020, I dont plan to support python 2 anymore.
